package com.demo.common.model;

import com.demo.common.model.base.BaseChildpackagelist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Childpackagelist extends BaseChildpackagelist<Childpackagelist> {
	public static final Childpackagelist dao = new Childpackagelist().dao();
}
