package com.demo.common.model;

import com.demo.common.model.base.BaseCompany;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Company extends BaseCompany<Company> {
	public static final Company dao = new Company().dao();
}
