package com.demo.common.model;

import com.demo.common.model.base.BaseMotherpackagelist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Motherpackagelist extends BaseMotherpackagelist<Motherpackagelist> {
	public static final Motherpackagelist dao = new Motherpackagelist().dao();
	
	
}
