package com.demo.common.model;

import com.demo.common.model.base.BasePacking;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Packing extends BasePacking<Packing> {
	public static final Packing dao = new Packing().dao();
}
