package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCompany<M extends BaseCompany<M>> extends Model<M> implements IBean {

	public M setCompanyid(java.lang.Integer companyid) {
		set("companyid", companyid);
		return (M)this;
	}
	
	public java.lang.Integer getCompanyid() {
		return getInt("companyid");
	}

	public M setCompanyname(java.lang.String companyname) {
		set("companyname", companyname);
		return (M)this;
	}
	
	public java.lang.String getCompanyname() {
		return getStr("companyname");
	}

}
