package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMotherpackagelist<M extends BaseMotherpackagelist<M>> extends Model<M> implements IBean {

	public M setMotherpackageid(java.lang.Integer motherpackageid) {
		set("motherpackageid", motherpackageid);
		return (M)this;
	}
	
	public java.lang.Integer getMotherpackageid() {
		return getInt("motherpackageid");
	}

	public M setMothergamename(java.lang.String mothergamename) {
		set("mothergamename", mothergamename);
		return (M)this;
	}
	
	public java.lang.String getMothergamename() {
		return getStr("mothergamename");
	}

	public M setMothergamepackagename(java.lang.String mothergamepackagename) {
		set("mothergamepackagename", mothergamepackagename);
		return (M)this;
	}
	
	public java.lang.String getMothergamepackagename() {
		return getStr("mothergamepackagename");
	}

	public M setMothergamesocurceid(java.lang.String mothergamesocurceid) {
		set("mothergamesocurceid", mothergamesocurceid);
		return (M)this;
	}
	
	public java.lang.String getMothergamesocurceid() {
		return getStr("mothergamesocurceid");
	}

	public M setMothergamebelongprojectname(java.lang.String mothergamebelongprojectname) {
		set("mothergamebelongprojectname", mothergamebelongprojectname);
		return (M)this;
	}
	
	public java.lang.String getMothergamebelongprojectname() {
		return getStr("mothergamebelongprojectname");
	}

	public M setMothergameplatformid(java.lang.String mothergameplatformid) {
		set("mothergameplatformid", mothergameplatformid);
		return (M)this;
	}
	
	public java.lang.String getMothergameplatformid() {
		return getStr("mothergameplatformid");
	}

	public M setBelongcompany(java.lang.Integer belongcompany) {
		set("belongcompany", belongcompany);
		return (M)this;
	}
	
	public java.lang.Integer getBelongcompany() {
		return getInt("belongcompany");
	}

	public M setApkpath(java.lang.String apkpath) {
		set("apkpath", apkpath);
		return (M)this;
	}
	
	public java.lang.String getApkpath() {
		return getStr("apkpath");
	}

	public M setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
		return (M)this;
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

}
